### ISSUE TITLE
got i18n - from user Markus

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_extended_selection#3]
[cuda_extended_selection.zip](https://github.com/halfbrained/cuda_extended_selection/files/5899515/cuda_extended_selection.zip)

**Comment by Alexey-T** [comment]
@halfbrained Pls apply this i18n patch?

**Comment by halfbrained** [comment]
~~You shouldn't rush people, perfection takes time :D~~

Done. My apologies for the delay. Thanks Markus.
